[package]
name = "co/project-101"  
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
maid = "flamenco687/maid@3.2.2"
zone = "chabba100/zone@5.0.6"
