name: Code Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Super-Linter
        uses: super-linter/super-linter@v4.9.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_LUA: true
          LUA_LINTER: luacheck
          VALIDATE_ALL_CODEBASE: true
